version: '3.9'

services:
  seq:
    image: datalust/seq:latest
    container_name: "seq"
    volumes:
      - ~/apps/seq/data:/data
    ports:
      - '5341:80'
    environment:
      - ACCEPT_EULA=Y

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: "mssql-db"
    ports:
      - 5432:1433
    volumes:
      - ~/apps/mssql/data:/var/lib/mssql/data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=AdminKwetter321
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge

  gateway-network:
    name: gateway-network